<?php 
	include "vendor/views/header/header.blade.php"; 
	$GetApis = mysqli_query($ConClass, "SELECT * FROM `merchants` WHERE `user_id`='$Auth'");
?>
<style>
	.bootstrap-select{
		width: 230px !important;
	}
	.btn-light {
		color: #212529;
		background-color: #ffffff;
		border-color: #c7cbd3;
		box-shadow: unset;
		padding-left: 20px !important;
		padding-right: 20px !important;
		padding-top: 0px !important;
		padding-bottom: 0px !important;
	}
	.sckey{
		-webkit-text-security: disc;
		font-size: 15px;
		display: none;
	}
	.sckeyrel{
		-webkit-text-security: none !important;
		font-size: 15px;
		display: block !important;
	}
</style>
     <div class="content-page">
     <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="d-flex flex-wrap align-items-center justify-content-between mb-4">
                    <div>
                        <h4 class="mb-3">Marchent Application Keys</h4>
                        <p class="mb-0">These keys will allow you to authenticate API requests</p>
                    </div>
                    <div class="form-group">
						<label> Select Your APP </label><br />
                        <form id="GetAPIs">
						<select class="selectpicker form-control" name="appid" id="appid" style="width: 200px !important;">
							<option value="" disabled selected>SELECT APP</option>
							<?php 
								while($GAPI = mysqli_fetch_assoc($GetApis)){
							?>
							<option value="<?php echo $GAPI['APP_ID']; ?>"><?php echo $GAPI['APP_ID']; ?></option>
							<?php } ?>
						</select>
						<br />
						<input type="hidden" name="Auth" value="<?php echo $_SESSION['UserId']; ?>">
						<input type="submit" id="sbfm" style="display: none;">
						</form>
					</div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="table-responsive rounded mb-3">
                <table class="table mb-0 tbl-server-info">
                    <thead class="bg-white text-uppercase">
                        <tr class="ligth ligth-data">
                            <th>App ID</th>
                            <th>Publish Key</th>
                            <th>Secrate Key</th>
                        </tr>
                    </thead>
                    <tbody class="ligth-body" id="ApiDetails">
                        
                        
                    </tbody>
                </table>
                </div>
            </div>
			<hr />
			<div class="col-lg-12">
				<h4 style="text-transform: uppercase; font-family: 'Exo 2'; margin-top: 27px; margin-bottom: 10px">Payments</h4>
				<div style="text-transform: ; font-family: 'Exo 2'; ">
					<p>LDFA payments can be processed across multiple channels, including online, in-app, and in-person. The LDFA developer platform includes server-side APIs that support online payments and mobile SDKs that support mobile payments on seller or buyer mobile devices.<p />
					<ul>
						<li>Online payments comprise a web client that accepts a buyer’s payment card, digital wallet payments, LDFA Gift Card, or bank transfer and a seller-hosted backend that processes the payment using the payment token generated by the web client. The payment is credited to the seller associated with the OAuth token used in the LDFA API call on the backend.</li>
						<li>Accept in-application payments on a seller-created mobile application and installed on a buyer's Android or iOS device. Buyers use the application to check out purchases and enter payment card information. When the checkout is complete, the application sends a secure payment token to the seller backend for payment.</li>
					</ul>
				</div>
			</div>
        </div>
        <!-- Page end  -->
    </div>
    
      </div>
    </div>
	<div class="modal fade" id="new-app" tabindex="-1" role="dialog" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document" style="max-width: 700px;">
              <div class="modal-content">
				  <div class="modal-header">
					<h5 class="header-mb-3">New Application</h5>
				  </div>
                  <div class="modal-body">
                      <div class="popup text-left">
                          <div class="content create-workform bg-body">
                              <div class="form-row">
								  <div class="col-md-6">
									  <label class="mb-2">APP Name</label>
									  <input type="text" class="form-control" name="app_name" placeholder="Enter Name or Email">
								  </div>
								  <div class="col-md-6">
									  <label class="mb-2">Site URL</label>
									  <input type="text" class="form-control" name="site_url" placeholder="Enter Name or Email">
								  </div>
                              </div>
							  <div class="form-row">
								  <div class="col-md-6">
									  <label class="mb-2">API Success Link</label>
									  <input type="text" class="form-control" name="success_link" placeholder="Enter Name or Email">
								  </div>
								  <div class="col-md-6">
									  <label class="mb-2">API Fail Link</label>
									  <input type="text" class="form-control" name="fail_link" placeholder="Enter Name or Email">
								  </div>
                              </div>
							  <div class="form-row">
								  <div class="col-md-6">
									  <label class="mb-2">Logo</label>
									  <input type="text" class="form-control" name="logo_url" placeholder="Enter Name or Email">
								  </div>
								  <div class="col-md-6">
									  <label class="mb-2">Thumb</label>
									  <input type="text" class="form-control" name="thumb" placeholder="Enter Name or Email">
								  </div>
                              </div>
							  <div class="form-row">
								  <div class="col-md-12">
									  <label class="mb-2">Description</label>
									  <textarea type="text" name="description" class="form-control"></textarea>
								  </div>
                              </div>
							  <div class="modal-footer">
								  <div class="col-lg-12">
									  <div class="d-flex flex-wrap align-items-ceter justify-content-center">
										  <div class="btn btn-primary mr-4" data-dismiss="modal">Cancel</div>
										  <div class="btn btn-outline-primary" data-dismiss="modal">Create Application</div>
									  </div>
								  </div>
							  </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
	  <script>
		$(document).ready(function(){
			$("#reveal").click(function(){
				$("#sekey").addClass("sckeyrel");
				$("#reveal").hide();
			});
			$("#appid").change(function(){
				$("#sbfm").click();
			})
			
		});
	  </script>
	  <script>
		$(document).ready(function(){
			$("#GetAPIs").submit(function(e){
				e.preventDefault();
					$.ajax({
						url: "vendor/Models/GetApisKeys.php",
						method: "post",
						data: $("#GetAPIs").serialize(),
						dataType: "html",
						success: function(strMessage){
						    $("#ApiDetails").html(strMessage);
						}
		    	});
			});
	    });
	</script>
  <?php include "vendor/views/footer/footer.blade.php"; ?>